buildkitd:
# Values for the buildkitd component (StatefulSet, Service, etc.)

  # annotations: for the buildkitd StatefulSet
  annotations: {}

  # dnsPolicy: for the buildkitd StatefulSet
  dnsPolicy: ""
  
  # dnsConfig: for the buildkitd StatefulSet
  dnsConfig: {}
    # nameservers:
    #   - 169.254.169.253 # AWS
    #   - 1.1.1.1 # Cloudflare
    #   - 8.8.8.8 # Google

  # replicaCount: Number of replicas for the buildkitd StatefulSet to deploy initially
  replicaCount: 0
  image:
    repository: earthly/buildkitd
    # renovate: datasource=docker depName=earthly/buildkitd
    tag: "v0.8.15" # Specify a recent stable tag for earthly/buildkitd. v0.13.1 as of May 2025.
    pullPolicy: IfNotPresent
  # Pod security context
  # fsGroup can be set here if needed
  podSecurityContext: {}
  #  fsGroup: 1001

  # initContainers: for the buildkitd StatefulSet
  initContainers: []
  # Example to enable qemu for multi-arch support
  # The following will configure the node to support all architectures
  # See https://github.com/moby/buildkit/blob/master/docs/multi-platform.md for more details
    # - name: binfmt-enable-qemu
    #   image: "tonistiigi/binfmt:qemu-v9.2.2"
    #   securityContext:
    #     privileged: true
    #   command: ["binfmt", "-install", "all"]

  # Container security context
  # Privileged mode is required for buildkitd
  containerSecurityContext:
    privileged: true
  # Resource requests and limits for the buildkitd container
  # It's highly recommended to set these according to your cluster capacity and workload
  resources: {}
    # requests:
    #   cpu: "500m"
    #   memory: "1Gi"
    # limits:
    #   cpu: "2000m"
    #   memory: "4Gi"
  # Persistence configuration for buildkitd cache
  persistence:
    enabled: true
    storageClassName: "" # Set to your preferred StorageClass (e.g., "gp3", "standard-rwo"). If "", uses default.
    size: 50Gi
    accessModes:
      - ReadWriteOnce
    mountPath: /tmp/earthly # Default mount path for buildkitd cache
  service:
    type: ClusterIP
    port: 8372 # Default buildkitd gRPC port
    portName: grpc # Name for the service port
    annotations: {}
    #  key: value
  # Additional environment variables to pass to the buildkitd container
  # Example:
  # extraEnvVars:
  #   - name: BUILDKIT_CACHE_MAX_SIZE_MB
  #     value: "10240" # 10GB
  extraEnvVars: []
  #  - name: SOME_OTHER_VAR
  #    value: "some_value"
  # extraArgs: extra arguments for the container entrypoint
  extraArgs: []
  #  - pass
  #  - some
  #  - args

  # Pod annotations for the buildkitd StatefulSet
  # Useful for Istio configuration or other integrations
  # Example for Istio:
  # podAnnotations:
  #   traffic.sidecar.istio.io/kubevirtInterfaces: "cni0"
  podAnnotations: {}

  # Node selection constraints
  nodeSelector: {}
  #  kubernetes.io/os: linux

  # Tolerations for pod scheduling
  tolerations: []
  # - key: "key"
  #   operator: "Exists"
  #   effect: "NoSchedule"

  # Additional volumes to mount into the buildkitd container
  # Example:
  # volumes:
  # - name: some-volume
  #   emptyDir: {}
  volumes: []
  # Additional volume mounts to add to the buildkitd container
  # Example:
  # volumeMounts:
  # - name: some-volume
  #   mountPath: /some/path
  volumeMounts: []

  # Affinity rules for pod scheduling
  affinity: {}

autoscaler:
  annotations: {}

  # replicaCount the number of autoscaler replicas to deploy
  # The autoscaler does not currently support more than one replica.
  # TODO: add support for multiple replicas
  replicaCount: 1

  image:
    repository: ghcr.io/o8t/buildkitd-proxy
    pullPolicy: IfNotPresent
    tag: v0.0.1

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  # Namespace to deploy all resources into. If not set, it defaults to the release namespace.
  # If set, the 00-namespace.yaml template will try to create it if namespace.create is true.
  namespaceOverride: ""

  namespace:
    create: true # Set to true to create the namespace defined in namespaceOverride or a default one if namespaceOverride is empty.

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  rbac:
    # Specifies whether RBAC resources (Role, RoleBinding) should be created
    create: true

  # Autoscaler application specific configuration
  # These will be set as environment variables in the deployment
  autoscalerConfig:
    # proxyListenAddr for the proxy service (e.g., ":8080" or ":8372")
    proxyListenAddr: ":8372"
    # scaleDownIdleTimeout for scaling down (e.g., "2m0s")
    scaleDownIdleTimeout: "2m0s"
    # readyWaitTimeout for buildkitd to become ready (e.g., "5m0s")
    readyWaitTimeout: "5m0s"
    logLevel: "debug" # Example, if you add log level config to the app

  service:
    type: ClusterIP
    port: 8372 # External port for the LoadBalancer/NodePort
    targetPort: 8372 # Internal port of the autoscaler (must match autoscalerConfig.proxyListenAddr port)
    # nodePort: # Specify if service.type is NodePort

  # Pod resource requests and limits
  resources: {}
    # requests:
    #   cpu: "100m"
    #   memory: "64Mi"
    # limits:
    #   cpu: "200m"
    #   memory: "128Mi"

  nodeSelector: {}

  tolerations: []

  affinity: {}

  extraArgs: []
  #  - pass
  #  - some
  #  - args
