apiVersion: v2
name: buildkitd-autoscaler
description: A Helm chart for the Kubernetes buildkitd autoscaler service
type: application
version: 0.1.0 # Initial chart version
appVersion: "1.0.0" # Version of the application itself
keywords:
  - buildkitd
  - autoscaler
  - kubernetes
  - proxy
home: https://github.com/your-repo/go-buildkitd-proxy # Replace with your actual repo URL
sources:
  - https://github.com/your-repo/go-buildkitd-proxy # Replace with your actual repo URL
maintainers:
  - name: YourName # Replace with your name/org
    email: your.email@example.com # Replace