apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default # Or buildkitd-scaler-system
  name: buildkitd-autoscaler-role
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "patch", "update"]
# Optional: Add "pods" if deeper inspection is ever needed
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["get", "list", "watch"]