{{- if .Values.autoscaler.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildkitd-stack.autoscaler.serviceAccountName" . }}
  labels:
    {{- include "buildkitd-stack.autoscaler.labels" . | nindent 4 }}
  {{- with .Values.autoscaler.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.autoscaler.serviceAccount.automountServiceAccountToken }}
{{- end }}