name: Publish Helm Chart

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on semver tags like v1.0.0, v1.2.3, etc.

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.0'
      
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Update chart version
        run: |
          sed -i "s/^version:.*/version: ${{ steps.version.outputs.VERSION }}/" helm/buildkitd-stack/Chart.yaml
          
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Package and publish chart
        run: |
          helm dependency update helm/buildkitd-stack
          helm package helm/buildkitd-stack --destination /tmp
          helm push /tmp/buildkitd-stack-${{ steps.version.outputs.VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts 